# ==============={ System Configurations }================
# Restart is required to changes to take affect!

verbose: true
# Enable Verbose Log for Debugging (and it looks cool so just enable it). Default: true
# Note that depenency checking cannot be hidden because it's a bootstrap of the system.

compatibilityMode: false
# Will disable config check, set to true if your vps can't run the script. Default: false
# What it does: disable readline, that's it..



# ============={ Bot Status Configurations }==============

status: Idle
# Show bot status such as Online, Idle, DnD, or Invisible (This will be overwritten by Streaming activity if set). Default: Online

activity: Listening
# Show bot status such as Listening, Streaming, Watching, Playing, and Competing. set false to disable

statusText: You ( ｡•̀ᴗ- ) ✧
# Show bot custom status text, activity must also be false if you want to disable this. set false to disable

statusSubText: Running v2.25.7.06-DEV
# Show second bot custom status text, both statusText and activity must be enabled for this to work. set false to disable

statusUrl: https://www.twitch.tv/lofigirl
# Show "Watch" button to spesified Twitch/Youtube Livestream, activity must be set to Streaming for this to work. set false to disable



# ================{ AI  Configurations }==================

AI: true
# Define if AI Features should be enabled or not. if disabled, will affect ALL FEATURES that include AI and stop Chat monitoring

slashAI: true
# Allow AI to also interact on supported slash command. set false to Decline
# Supported slash command: (To Do!)

chatModel: 'gemini-2.5-flash'
# Change the Default Model for casual chatting (Only Gemini is supported!). Default: gemini-2.5-flash

contextLimit: 100
# How many message AI used as context, More context = Slower Respond! Default: 100 (0 = Unlimited)

alwaysRespond: [ '1230804584235274291' ]
# Always respond to spesified Channel ID, multiple Channel ID can be added separated by comma. false to disable



# ==================={ Auto Respond }=====================

autoRespond: [ 'Pagi', 'Siang', 'Sore', 'Malem', 'Welcome', 'Sepi' ]
# Always respond if first 2 words contains these words, not case sensitive. false to disable

autoRespondCooldown: 3
# How many message(s) until next auto respond triggered. Default: 3 (0 = Always trigger auto respond)

alwaysIgnoreSymbol: '-#'
# Always ignore if contains specified character at start. (Also affect alwaysIgnore) Default: -#
  


# =================={ Slash Commands }====================

enablePing: true
# Define if /ping is enabled or not. True/False

enableOsu: true
# Define if osu! intergrations is enabled or not. True/False

enableAfk: true
# Define if /afk is enabled or not. True/False