# ============== General Configurations ===============
# Restart is required to changes to take affect!

debugMode: true
# Enable Verbose Log for Debugging. Default: false

compatibilityMode: false
# Will disable config check, set to true if your vps can't run the script. Default: false



# ============ Bot Account Configurations =============

status: DoNotDisturb
# Show bot status such as Online, Idle, DnD, or Invisible (This will be overwritten by Streaming activity if set).

activity: Streaming
# Show bot status such as Listening, Streaming, Watching, Playing, and Competing. set false to disable

statusText: 'Rikomunity'
# Show bot custom status text, activity must also be false if you want to disable this. set false to disable

statusUrl: https://www.twitch.tv/lofigirl
# Show Button to spesified Twitch/Youtube Live Stream for Streaming status. set false to disable



# ================ AI Configurations ==================

autoRespond: [ 'Pagi', 'Siang', 'Sore', 'Malem', 'Welcome', 'Sepi' ]
# Always respond if first 2 words contains these words. Not case sensitive

autoRespondCooldown: 3
# How many message(s) until next auto respond triggered. Default: 3 (0 = Always trigger auto respond)

alwaysRespond: [ '1230804584235274291' ]
# Always respond to spesified Channel ID. Multiple Channel ID can be added separated by comma

alwaysIgnoreSymbol: '-#'
# Always ignore if contains specified character at start. Default: -#

chatModel: 'gemini-2.5-flash'
# Change the Default Model for casual chatting (Only Gemini is supported!). Default: gemini-2.5-flash

contextLimit: 100
# How many message AI used as context, More context = Slower Respond! Default: 100 (0 = Unlimited)